version: '3'
services:
  #mongodb
  mongo_db:
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db
    restart: always

  #mongo-express
  mongo_express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ''
      ME_CONFIG_MONGODB_ADMINPASSWORD: ''
      ME_CONFIG_MONGODB_SERVER: mongo_db

    depends_on:
      - mongo_db

  #node
  node:
    build: ./server
    ports:
      - 5055:5000
    environment:
      - MONGO_URI=mongodb://mongo_db:27017
      - JWT_KEY=my_secret
    depends_on:
      - mongo_db

  #vite-react-app
  client:
    build: ./client
    ports:
      - 3033:3000
    environment:
      - REACT_APP_SERVER_URL=http://localhost:5055
    depends_on:
      - node


volumes:
  mongo_db: {}
